### ISSUE TITLE
Add option to set pixel size when downloading scenario rasters

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/lizard-qgis-plugin#37]
<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEhhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71afa4a6024caf7bf6e499575f2c6fa7456b8e26/image.png" alt="image.png" />

Logic should be the same as in the rasters tab (prepopulate from the value retrieved from Lizard if available, otherwise use 1 as default)

**Comment by leendertvanwolfswinkel** [comment]
I tried to download a max water depth from a scenario that is in EPSG:31370, while my project CRS was EPSG:28992. I got the following error.

I also tried the same using the production version of the Lizard plugin (same scenario and project crs), and there it works fine

```
An error has occurred while executing Python code: 

TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:   overload 1: too many arguments   overload 2: argument 2 has unexpected type 'str'   overload 3: argument 2 has unexpected type 'str'   overload 4: argument 2 has unexpected type 'str'   overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\lizard_qgis_plugin\widgets\lizard_archive_browser.py", line 419, in download_results
    unify_spatial_boundaries(scenario_instance, scenario_instance_crs, target_crs)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\lizard_qgis_plugin\utils.py", line 372, in unify_spatial_boundaries
    dst_point_geom = reproject_geometry(src_point_geom, source_crs, destination_crs)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\lizard_qgis_plugin\utils.py", line 358, in reproject_geometry
    transformation = QgsCoordinateTransform(src_crs, dst_crs, transform_context)
TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 2 has unexpected type 'str'
  overload 3: argument 2 has unexpected type 'str'
  overload 4: argument 2 has unexpected type 'str'
  overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'
```

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Fix pushed.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek tested it, please merge
